### ISSUE TITLE
srv#12576106  hw#12570558 Permission to upload kernel was denied

### ISSUE THREAD

**Issue by heathfx** [LegacyNsfw/PcmHacks#178]
I have a PCM from an '03 yukon with flex fuel (srv#12576106  hw#12570558) and when I tried to read it I recieved "Permission to upload kernel was denied".

Shouldn't this PCM be supported?

If I can help in any way let me know, I have a bench harness and a BDM interface on the way, I'm new to this as of last saturday, but I am rapidly educating myself after bricking my factory original PCM with HP tuners.

For a sanity check, I have a 411 PCM as well and was able to read it with PCM hammer without issue. I'm using a VXdiag nano gds2 interface.

any guidance would be amazing!

cheers!

**Comment by Gampyg28** [comment]
It is a supported PCM.

For further assistance please attach a Debug Log to a post on pcmhacking.net in either a new thread or one of the existing threads like: [PCM Hammer Release 014](https://pcmhacking.net/forums/viewtopic.php?f=42&t=6730#p99839)

Thank you!
