### ISSUE TITLE
vehicles useing P01 GTP 3800SC

### ISSUE THREAD

**Issue by canaminal** [LegacyNsfw/PcmHacks#267]
Im doing a motor swap 3800 SC  into Lesharo motorhome

 My PCM is a Delphi P01, I wonder if I can use PC Hammmer to remove IGN BCM and sterio from the loop so its a standalone 

 2006 pontiac gtp engine code E32

 I have motor and no car so...

**Comment by Gampyg28** [comment]
No ...

PCM Hammer only reads and writes the flash chip, it makes no changes to the resulting binary.

However, once you have used PCM Hammer to read the PCM, you can then use something like Tuner Pro and an XDF fille to modify the binary (.bin file), once you have used Tuner Pro (or whatever) to modify the bin you would then use PCM Hammer to write the modified file back to the PCM.

FMI see the abundance of knowledge on pcmhacking.net.

**Comment by antuspcm** [comment]
Please also check that your PCM is a P01. I believe the 3800 SC is normally a P04 which is not supported by PCM Hammer to read or write but it is possible someone has put a P01 with a V6 tune on it.

**Comment by Sc10Wolf** [comment]
I could also edit the bin file when you're able to get it off.
