### ISSUE TITLE
PCM  Logger won't log, but PCM Hammer will read and flash

### ISSUE THREAD

**Issue by dukenukemx** [LegacyNsfw/PcmHacks#274]
I was able to use PCM Hammer to make changes to my 02 Corvettes ECU, as I've had someone in the past tune my car and turn off a lot of things in the transmission.  Now I'm trying to log but I can't seem to do that.  I can get it to detect my OBDLink SX but once I try to log it doesn't.  I got PCM Logger off the Microsoft store, so I don't know of any other source to get it.  

This is the USB OBD tool I'm using to try and log.  I'm not sure if there's a log file that I can upload that shows this problem.  
https://www.amazon.com/dp/B005ZWM0R4?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by Gampyg28** [comment]
I can only assume the SX works, I believe NSFW has one ...

The Debug Tab is the log ... select all, copy paste to notepad, save as and attach the file.

PCM Logger is in pretty raw development, but it does work well ... Starting with it is a little rough ATM.
Open: PCM Logger
Select: Select Device (if required. and setup your device)
Select TAB: Parameters (add a few parameters (place check marks))
Select TAB: Profiles
Select: Save As (save the profile)
Close: PCM Logger
Open: PCM Logger
Select TAB: Parameters (it should be processing)
Select: Start Recording (to save to log)

BTW: The latest version is here: https://github.com/LegacyNsfw/PcmHacks/releases/download/2022.05.14.01/PcmHammer021.zip

-Enjoy

**Comment by dukenukemx** [comment]
Sorry I was able to get it working long ago.  Forgot about this.
