### ISSUE TITLE
Godiag nano compatibility 

### ISSUE THREAD

**Issue by 99zguy** [LegacyNsfw/PcmHacks#284]
Has there been any information on godiag nano working on either 1x or 4x?  Up to this point I can connect to PO1 411 pcm and see the osid etc.  No problems there.  If I read the entire pcm, it hangs up and errors after it unlocks and sets 4x speed.  It will not upload and tines out after this.  I have some log files I can upload in a bit

**Comment by Tazzi3** [comment]
@99zguy The issue will be relating to wiring plus power quality, both have major impact on the communication stability which is extremely critical when at 4x. Have seen this multiple times on various J2534 tools.

If this is being done in car, then other parts of the vehicle may be also causing the communication to drop back into 1x mode hence failing to read.

**Comment by 99zguy** [comment]
@Tazzi3   I have been attempting this on bench,  considered that pwr supply could be issue and have another one ill have in hand tomorrow that has adjustability that I will try with.  I also did go over the wiring with setup and all looks to be good.  

Also am having same issue when in 1x mode,  so it does not seem to be dependent on that.   Possible that the godiag nano just isnt capable?

[PcmHammer_debugLog_20230104@112023.txt](https://github.com/LegacyNsfw/PcmHacks/files/10349247/PcmHammer_debugLog_20230104%40112023.txt)

Here is one of the logs.

**Comment by alikhaled-microfoxdev** [comment]
> @Tazzi3 I have been attempting this on bench, considered that pwr supply could be issue and have another one ill have in hand tomorrow that has adjustability that I will try with. I also did go over the wiring with setup and all looks to be good.
> 
> Also am having same issue when in 1x mode, so it does not seem to be dependent on that. Possible that the godiag nano just isnt capable?
> 
> [PcmHammer_debugLog_20230104@112023.txt](https://github.com/LegacyNsfw/PcmHacks/files/10349247/PcmHammer_debugLog_20230104%40112023.txt)
> 
> Here is one of the logs.

same exact issue literally the same LOG file  using (godiag gd101) j2534 usb interface  :(

**Comment by antuspcm** [comment]
Godiag nano is known not compatible, and not 100% compliant wth J2534 specs. Their devs have said to one person that they are working on it, but no update for a while and currently there is no solution. We would recommend a higher quality interface. For details see the thread here: https://pcmhacking.net/forums/viewtopic.php?f=42&t=8058
