### ISSUE TITLE
unable to reconnect obd link lx

### ISSUE THREAD

**Issue by danmcdonal** [LegacyNsfw/PcmHacks#291]
pcm opens and will not let me chose which serial port, the click down comes up and it no longer has any options to choose from, any help? im trying to use my obdlink LX

**Comment by Gampyg28** [comment]
I would venture a guess that you have Serial Port (COM port) issues, like the OBDLink LX is not being recognized.
PCMHammer can only find Installed Serial Ports.

The OBDLink LX is known to work with PCMHammer.
Maybe you have a bad one ...

Plug it in, look in Device Manager under 'Ports' and see if there is a port for it

-Enjoy
