### ISSUE TITLE
03

### ISSUE THREAD

**Issue by Mdt5** [LegacyNsfw/PcmHacks#341]
OBD-II
ECU protocol: 2) SAE J1850 VPW (10.4 kbaud)
ECU address/CAN Id: 10
Calibration Verification Numbers: 0010000FA22A6486B104906020000E765D486B1049060300006E623486B10490604000035CFC486B1049060500007739E486B104906060000BDFAA486B1049060700007FA89486B10490608000063B00
Calibration ID: 
1257±#CHkId±@@Hk127d±@cscHkIÔ@
HI	257¤±@C3skI±ÀHkI
125¤±@ãSCRHk¤±AHkI1574A#CV4±AkI±S#SHkI835±ApHkD±AStäA£SsHIô±AkI1257±ã#S#HkID±B
VIN: HGCET3H317S

**Comment by antuspcm** [comment]
not supported, and/or junk post.

**Comment by antuspcm** [comment]
not support and/or junk post
