### ISSUE TITLE
Can anyone recommend a USB device that is compatible with the software and gm 0411 ECU?

### ISSUE THREAD

**Issue by james28909** [LegacyNsfw/PcmHacks#348]
Title says it all. Am having trouble finding a legit device that I think will work. If some people can post what worked for them on the 0411 ECU for gm ~2000ish year model? 

I feel like I can't find a detailed list that explains this very well. Any information sure would be appreciated.

**Comment by antuspcm** [comment]
First, figure out what type of PCM you have, including service number. ish might get you in to trouble if its something that is not supported.

Next, for anyone that sees it, the application will be moving in the near future to the pcmhammer organisation here: https://github.com/PcmHammer/PcmHammer/
As of this day the version on that site is not yet release, but it incorporates support for some newer PCMs.

Best bang for buck interface is obdxpro, if you use this affiliate link to buy one, then we make a couple of cents we can put toward developing the application further:  https://obdxpro.com?ref=pcmhacking
