### ISSUE TITLE
Flash chip ID logic doesn't work for AMD chips.

### ISSUE THREAD

**Issue by LegacyNsfw** [LegacyNsfw/PcmHacks#90]
This is blocking P59 write support.

**Comment by antuspcm** [comment]
In theory but the hardware isnt doing what I expect. Its an AM29F800B. Ive posted up data sheets for most the main ICs at https://pcmhacking.net/forums/viewtopic.php?f=42&t=6209

**Comment by LegacyNsfw** [comment]
I was just talking online with a guy who is working on a Lotus ECU that has the same AMD flash chip in it, and he had a couple of interesting ideas. First, look for flash routines in the existing firmware (it's in there to safe OBD2 faults) and should be easy to find by searching for the values that enter command mode (0xAAAA, 0x5555). Second, he posted the flash routines from the ECU he's working on. 

Antus, I bet it would be interesting to compare that to the current kernel code. It's near the end of this thread:

http://www.romraider.com/forum/viewtopic.php?f=7&t=14805&p=141013

**Comment by antuspcm** [comment]
Hmm yeah that looks about right. I have located existing code, but I think we are hitting timing issues. Our C implementation generates code that is not as optimised as the factory code and executes more slowly. I think that may be why we dont get the same results, whereas the intel chip is more tollerant. We may need to use #pragma asm or similar to do this direct.
